services:

    mongodb:
        image: mongo:7
        container_name: pppk_birdnet_mongodb
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DB}
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db
        networks:
            - birdnet

    minio:
        image: minio/minio:latest
        container_name: pppk_birdnet_minio
        restart: unless-stopped
        environment:
            MINIO_ROOT_USER: ${MINIO_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
        ports:
            - "9000:9000" #API
            - "9001:9001" #WebUI
        volumes:
            - minio_data:/data
        command: server /data --console-address ":9001"
        networks:
            - birdnet

volumes:
    mongodb_data:
    minio_data:

networks:
    birdnet:
        driver: bridge
