name: PPPK BirdNET Pipeline

on:
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    env:
      MONGO_USER: ${{ secrets.MONGO_USER }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      MONGO_DB: ${{ secrets.MONGO_DB }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      MINIO_USER: ${{ secrets.MINIO_USER }}
      MINIO_PASSWORD: ${{ secrets.MINIO_PASSWORD }}
      MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}
      MINIO_BUCKET: ${{ secrets.MINIO_BUCKET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start services (docker compose)
        run: docker compose up -d

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for services
        run: sleep 20

      - name: Run pipeline
        run: snakemake --cores 1

      - name: Stop services
        if: always()
        run: docker compose down